config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-status/web'
if Octobox.config.sidekiq_schedule_enabled?
  require 'sidekiq-scheduler/web'
end
require 'admin_constraint'

Rails.application.routes.draw do
  root to: 'notifications#index'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  constraints AdminConstraint.new do
    namespace :admin do
      mount Sidekiq::Web => "/sidekiq"
    end

    get '/admin', to: 'admin#index', as: :admin
  end

  get :login,  to: 'sessions#new'
  get :logout, to: 'sessions#destroy'

  scope :auth do
    match '/:provider/callback', to: 'sessions#create',  via: [:get, :post]
    match :failure,              to: 'sessions#failure', via: [:get, :post]
  end

  resources :notifications, only: :index, format: true, constraints: { format: :json }
  resources :notifications, only: [] do
    collection do
      post :archive_selected
      post :sync
      get  :sync
      get  :syncing
      post :mute_selected
      post :mark_read_selected
      get  :unread_count
      post :delete_selected
    end

    member do
      post :star
      post :mark_read
    end
  end

  get '/documentation', to: 'pages#documentation'
  get '/support', to: redirect('/documentation#support')

  post '/hooks/github', to: 'hooks#create'

  if Octobox.octobox_io?
    get '/pricing', to: 'pages#pricing'
    get '/privacy', to: 'pages#privacy'
    get '/terms', to: 'pages#terms'
  end

  resources :pinned_searches

  get '/settings', to: 'users#edit'
  resources :users, only: [:update, :destroy] do
    collection do
      scope format: true, constraints: { format: 'json' } do
        get :profile
      end
    end
  end
end

app/models/notification.rb
# frozen_string_literal: true
class Notification < ApplicationRecord

  include Octobox::Notifications::InclusiveScope
  include Octobox::Notifications::ExclusiveScope
  include Octobox::Notifications::SyncSubject
  include Octobox::Notifications::SyncRepository

  SUBJECTABLE_TYPES = SUBJECT_TYPE_COMMIT_RELEASE + SUBJECT_TYPE_ISSUE_REQUEST.values

  if DatabaseConfig.is_postgres?
    include PgSearch
    pg_search_scope :search_by_subject_title,
                    against: :subject_title,
                    order_within_rank: 'notifications.updated_at DESC',
                    using: {
                      tsearch: {
                        prefix: true,
                        negation: true,
                        dictionary: "english"
                      }
                    }
  else
    def self.search_by_subject_title(title)
      where('subject_title like ?', "%#{title}%")
    end
  end

  belongs_to :user
  belongs_to :subject, foreign_key: :subject_url, primary_key: :url, optional: true
  belongs_to :repository, foreign_key: :repository_full_name, primary_key: :full_name, optional: true
  has_many :labels, through: :subject

  validates :subject_url, presence: true
  validates :archived, inclusion: [true, false]

  paginates_per 20

  class << self
    def attributes_from_api_response(api_response)
      attrs = DownloadService::API_ATTRIBUTE_MAP.map do |attr, path|
        value = api_response.to_h.dig(*path)
        value.delete!("\u0000") if value.is_a?(String)
        [attr, value]
      end.to_h
      if "RepositoryInvitation" == api_response.subject.type
        attrs[:subject_url] = "#{api_response.repository.html_url}/invitations"
      end
      attrs[:updated_at] = Time.current if api_response.updated_at.nil?
      attrs
    end
  end

  def title
    body = subject.try(:body)
    body.split("\n")[0..3].join if body
  end

  def state
    return unless display_subject?
    subject.try(:state)
  end

  def self.archive(notifications, value)
    value = value ? ActiveRecord::Type::Boolean.new.cast(value) : true
    notifications.update_all(archived: value)
    mark_read(notifications)
  end

  def self.mark_read(notifications)
    unread = notifications.select(&:unread)
    return if unread.empty?
    user = unread.first.user
    MarkReadWorker.perform_async_if_configured(user.id, unread.map(&:github_id))
    where(id: unread.map(&:id)).update_all(unread: false)
  end

  def self.mark_read_on_github(user, notification_ids)
    conn = user.github_client.client_without_redirects
    manager = Typhoeus::Hydra.new(max_concurrency: Octobox.config.max_concurrency)
    begin
      conn.in_parallel(manager) do
        notification_ids.each do |id|
            conn.patch "notifications/threads/#{id}"
        end
      end
    rescue Octokit::Forbidden, Octokit::NotFound
      # one or more notifications are for repos the user no longer has access to
    end
  end

  def self.mute(notifications)
    return if notifications.empty?
    user = notifications.to_a.first.user
    MuteNotificationsWorker.perform_async_if_configured(user.id, notifications.map(&:github_id))
    where(id: notifications.map(&:id)).update_all(archived: true, unread: false, muted_at: Time.current)
  end

  def self.mute_on_github(user, notification_ids)
    conn = user.github_client.client_without_redirects
    manager = Typhoeus::Hydra.new(max_concurrency: Octobox.config.max_concurrency)
    begin
      conn.in_parallel(manager) do
        notification_ids.each do |id|
          conn.patch "notifications/threads/#{id}"
          conn.put "notifications/threads/#{id}/subscription", {ignored: true}.to_json
        end
      end
    rescue Octokit::Forbidden, Octokit::NotFound
      # one or more notifications are for repos the user no longer has access to
    end
  end

  def expanded_subject_url
    return subject_url unless display_subject?
    subject.try(:html_url) || subject_url # Use the sync'd HTML URL if possible, else the API one
  end

  def web_url
    Octobox::SubjectUrlParser.new(expanded_subject_url, latest_comment_url: latest_comment_url)
      .to_html_url
  end

  def repo_url
    "#{Octobox.config.github_domain}/#{repository_full_name}"
  end

  def unarchive_if_updated
    return unless self.archived?
    change = changes['updated_at']
    return unless change
    if self.archived && change[1] > change[0]
      self.archived = false
    end
  end

  def update_from_api_response(api_response, unarchive: false)
    attrs = Notification.attributes_from_api_response(api_response)
    self.attributes = attrs
    self.archived = false if archived.nil? # fixup existing records where archived is nil
    unarchive_if_updated if unarchive
    save(touch: false) if changed?
    update_subject
    update_repository
  end

  def github_app_installed?
    Octobox.github_app? && user.github_app_authorized? && repository.try(:display_subject?)
  end

  def subjectable?
    SUBJECTABLE_TYPES.include?(subject_type)
  end

  def display_subject?
    @display_subject ||= subjectable? && (Octobox.fetch_subject? || github_app_installed?)
  end

  def upgrade_required?
    return nil unless repository.present?
    repository.private? && !repository.required_plan_available?
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  REASON_LABELS = {
    'comment'        => 'primary',
    'author'         => 'success',
    'state_change'   => 'info',
    'mention'        => 'warning',
    'assign'         => 'danger',
    'subscribed'     => 'subscribed',
    'team_mention'   => 'team_mention',
    'security_alert' => 'security_alert'
  }.freeze

  STATE_LABELS = {
    'open'   => 'success',
    'closed' => 'danger',
    'merged' => 'subscribed'
  }

  SUBJECT_TYPES = {
    'RepositoryInvitation'         => 'mail-read',
    'Issue'                        => 'issue-opened',
    'PullRequest'                  => 'git-pull-request',
    'Commit'                       => 'git-commit',
    'Release'                      => 'tag',
    'RepositoryVulnerabilityAlert' => 'alert'
  }.freeze

  SUBJECT_STATUS = {
    success: "success",
    failure: "failure",
    error: "error",
    pending: "pending"
  }

  NOTIFICATION_STATUS_OCTICON = {
    'success' => 'check',
    'failure' => 'x',
    'error' => 'alert',
    'pending' => 'primitive-dot'
  }

  def filters
    {
      reason:     params[:reason],
      unread:     params[:unread],
      repo:       params[:repo],
      type:       params[:type],
      archive:    params[:archive],
      starred:    params[:starred],
      owner:      params[:owner],
      per_page:   params[:per_page],
      q:          params[:q],
      state:      params[:state],
      label:      params[:label],
      author:     params[:author],
      bot:        params[:bot],
      unlabelled: params[:unlabelled],
      assigned:   params[:assigned],
      is_private: params[:is_private],
      status:     params[:status]
    }
  end

  def inbox_selected?
    !archive_selected? && !starred_selected? && !showing_search_results?
  end

  def archive_selected?
    filters[:archive].present?
  end

  def starred_selected?
    filters[:starred].present?
  end

  def showing_search_results?
    filters[:q].present?
  end

  def show_archive_icon?
    starred_selected? || showing_search_results?
  end

  def notification_param_keys
    filters.keys - [:per_page]
  end

  def bucket_param_keys
    [:archive, :starred]
  end

  def filter_param_keys
    notification_param_keys - bucket_param_keys
  end

  def any_active_filters?
    filter_param_keys.any?{|param| filters[param].present? }
  end

  def filtered_params(override = {})
    filters.merge(override)
  end

  def mute_selected_button
    function_button('Mute selected', 'mute', 'mute_selected', 'Mute selected items')
  end

  def mark_read_selected_button
    function_button('Mark as read', 'eye', 'mark_read_selected', 'Mark items as read')
  end

  def archive_selected_button
    function_button("Archive selected", 'checklist', "archive_toggle archive_selected", 'Archive selected items')
  end

  def unarchive_selected_button
    function_button("Unarchive selected", 'inbox', "archive_toggle unarchive_selected", 'Unarchive selected items')
  end

  def delete_selected_button
    function_button("Delete selected", 'trashcan', "delete_selected", 'Delete selected items')
  end

  def select_all_button(cur_selected, total)
    button_tag(type: 'button', class: "select_all btn btn-sm btn-outline-dark hidden-button", 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': "Number of items selected") do
      octicon('check', height: 16) +
        content_tag(:span, " #{cur_selected}", class: 'bold d-none d-md-inline-block ml-1') +
        " | " +
        content_tag(:span, " #{total}", class: 'd-none d-md-inline-block')
    end if cur_selected < total
  end

  def function_button(title, octicon, css_class, tooltip)
    button_tag(type: 'button', class: "#{css_class} btn btn-sm btn-outline-dark hidden-button", 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': tooltip ) do
      octicon(octicon, height: 16) + content_tag(:span, "#{title}", class: 'd-none d-md-inline-block ml-1')
    end
  end

  def no_url_filter_parameters_present
    notification_param_keys.all?{|param| params[param].blank? }
  end

  def notification_icon(subject_type, state = nil)
    state = nil unless display_subject?
    return 'issue-closed' if subject_type == 'Issue' && state == 'closed'
    return 'git-merge' if subject_type == 'PullRequest' && state == 'merged'
    SUBJECT_TYPES[subject_type]
  end

  def notification_icon_title(subject_type, state = nil)
    return subject_type.underscore.humanize if state.blank?
    "#{state.underscore.humanize} #{subject_type.underscore.humanize.downcase}"
  end

  def notification_icon_color(state)
    {
      'open' => 'text-success',
      'closed' => 'text-danger',
      'merged' => 'text-subscribed'
    }[state]
  end

  def reason_label(reason)
    REASON_LABELS.fetch(reason, 'secondary')
  end

  def state_label(state)
    STATE_LABELS.fetch(state, 'secondary')
  end

  def filter_option(param)
    if filters[param].present?
      link_to root_path(filters.except(param)), class: "btn btn-sm btn-outline-dark" do
        concat octicon('x', :height => 16)
        concat ' '
        concat yield
      end
    end
  end

  def reason_filter_option(reason)
    if filters[:reason].present? && reason.present?
      reasons = filters[:reason].split(',').reject(&:empty?)
      index = reasons.index(reason.underscore.downcase)
      reasons.delete_at(index) if index
      link_to root_path(filters.merge(:reason => reasons.join(','))), class: "btn btn-sm btn-outline-dark" do
        concat octicon('x', :height => 16)
        concat ' '
        concat yield
      end
    end
  end

  def filter_link(param, value, count)
    sidebar_filter_link(active: params[param] == value.to_s, param: param, value: value, count: count) do
      yield
    end
  end

  def org_filter_link(param, value)
    sidebar_filter_link(active: params[param] == value.to_s, param: param, value: value, except: :repo, link_class: 'owner-label') do
      yield
    end
  end

  def repo_filter_link(param, repo_name, count)
    active = params[param] == repo_name || params[:owner] == repo_name.split('/')[0]
    sidebar_filter_link(active: active, param: param, value: repo_name, count: count, except: :owner, link_class: 'repo-label', title: repo_name) do
      yield
    end
  end

  def sidebar_filter_link(active:, param:, value:, count: nil, except: nil, link_class: nil, path_params: nil, title: nil)
    content_tag :li, class: (active ? 'nav-item active' : 'nav-item'), title: title do
      active = (active && not_repo_in_active_org(param))
      path_params ||= filtered_params(param => (active ? nil : value)).except(except)
      link_to root_path(path_params), class: (active ? "nav-link active filter #{link_class}" : "nav-link filter #{link_class}") do
        yield
        if active && not_repo_in_active_org(param)
          concat content_tag(:span, octicon('x', :height => 16), class: 'badge badge-light')
        elsif count.present?
          concat content_tag(:span, count, class: 'badge badge-light')
        end
      end
    end
  end

  def reason_filter_link(value, count)
    active = params[:reason].present? && params[:reason].split(',').include?(value.to_s)
    link_value = reason_link_param_value(params[:reason], value, active)
    path_params = filtered_params(:reason => link_value)

    sidebar_filter_link(active: active, param: :reason, value: link_value, count: count, path_params: path_params) do
      yield
    end
  end

  def reason_link_param_value(param, value, active)
    reasons = param.try(:split, ',') || []
    active ? reasons.delete(value) : reasons.push(value)
    reasons.try(:join, ',')
  end

  def not_repo_in_active_org(param)
    return true unless param == :repo
    params[:owner].blank?
  end

  def search_query_matches?(query, other_query)
    query.split(' ').sort == other_query.split(' ').sort
  end

  def search_pinned?(query)
    return unless query.present?
    return false if current_user.pinned_searches.empty?

    current_user.pinned_searches.any? do |pinned_search|
      search_query_matches?(query, pinned_search.query)
    end
  end

  def notification_status(status)
    return unless status.present?
    content_tag(:span,
      octicon(NOTIFICATION_STATUS_OCTICON[status], height: 16, class: status),
      class: "badge badge-light badge-pr #{status}",
      title: status.humanize,
      data: {toggle: 'tooltip'}
    )
  end

  def sidebar_notification_status(status)
    octicon(NOTIFICATION_STATUS_OCTICON[status], height: 16, class: "sidebar-icon #{status}")
  end

end

app/views/notifications/_app_prompt.html.erb
<p>
  Pull in state, labels, authors, assignees and CI status on issues and pull requests by installing the GitHub App on
  <%= notification.repository_full_name %>.
</p>

<a href='<%= Octobox.config.app_url %>' class='btn btn-primary btn-sm'>Install the GitHub App</a>

app/views/notifications/_login_prompt.html.erb
<p>
  The GitHub App is installed on this repository, authorize it to see state, labels, authors, assignees and CI status on this notification.
</p>

<a href='/auth/githubapp' class='btn btn-primary btn-sm'>Login to the GitHub App</a>

app/views/notifications/_notification.html.erb
<tr id='notification-<%= notification.id %>' class='notification <%= notification.unread ? 'active' : '' %>'>
  <td class='notification-checkbox align-middle'>
    <div class="custom-control custom-checkbox">
      <%= check_box_tag(
          "notification_#{notification.id}",
          notification.id,
          false,
          title: (notification.archived ? 'Unarchive' : 'Archive'),
          class: 'custom-control-input ' + (notification.archived ? 'unarchive' : 'archive')
        )
      %>
      <%= label_tag "notification_#{notification.id}", '', class: "custom-control-label" %>
    </div>
  </td>
  <td class='notification-star align-middle'>
    <%= octicon 'star', height: 18, class: "toggle-star #{notification.starred ? 'star-active' : 'star-inactive'}", data: { id: notification.id, toggle: 'tooltip' }, title: notification.starred ? 'Remove star' : 'Star' %>
  </td>

  <% if show_archive_icon? %>
    <td class='notification-archived align-middle'>
      <% if notification.archived? %>
        <%= octicon 'archive', height: 16, data: { toggle: 'tooltip' }, title: 'Archived' %>
      <% end %>
    </td>
  <% end %>

  <td class='notification-icon align-middle <%= notification_icon_color(notification.state) if notification.display_subject? %>'>
    <% if Octobox.github_app? && notification.subjectable? %>
      <% if notification.repository.try(:github_app_installed?) && !current_user.github_app_authorized? %>
        <a tabindex="0" class="" role="button" data-toggle="popover" title="Login to the GitHub App" data-content="<%= render 'login_prompt' %>">
          <%= octicon notification_icon(notification.subject_type, notification.state), :height => 16 %>
        </a>
      <% elsif !notification.repository.try(:github_app_installed?) %>
        <a tabindex="0" class="" role="button" data-toggle="popover" title="Get more info for this <%= notification_icon_title(notification.subject_type, notification.state) %>" data-content="<%= render 'app_prompt', notification: notification %>">
          <%= octicon notification_icon(notification.subject_type, notification.state), :height => 16 %>
        </a>
      <% elsif Octobox.octobox_io? && notification.upgrade_required? %>
        <a tabindex="0" class="" role="button" data-toggle="popover" title="Subscribe Now" data-content="<%= render 'private_repos' %>">
          <%= octicon notification_icon(notification.subject_type, notification.state), :height => 16 %>
        </a>
      <% else %>
        <%= octicon notification_icon(notification.subject_type, notification.state), :height => 16, title: notification_icon_title(notification.subject_type, notification.state), data: {toggle: 'tooltip'} %>
      <% end %>
    <% else %>
      <%= octicon notification_icon(notification.subject_type, notification.state), :height => 16, title: notification_icon_title(notification.subject_type, notification.state), data: {toggle: 'tooltip'} %>
    <% end %>
  </td>
  <td class='notification-subject'>
    <%= link_to notification.subject_title, notification.web_url, target: (Octobox.config.open_in_same_tab ? nil : '_blank'), rel: "noopener", class: 'link', onclick: "Octobox.markRead(#{notification.id})", title: notification.title %>

    <% if notification.display_subject? %>
      <% if notification.subject %>
        <% notification.subject.labels.each do |label| %>
          <%= link_to emojify(label.name), root_path(filtered_params(label: label.name)), class: "badge d-sm", style: "background-color: ##{label.color}; color: #{label.text_color}" %>
        <% end %>
        <%= notification_status(notification.subject.status) %>
      <% end %>
    <% end %>
  </td>
  <% unless params[:repo].present? %>
    <td class='notification-repo'>
      <small>
        <%= link_to notification.repository_full_name, root_path(filtered_params(repo: notification.repository_full_name)), class: 'text-muted' %>
      </small>
    </td>
  <% end %>

  <td class='notification-subject-author'>
    <% if notification.display_subject? %>
      <% if notification.subject && notification.subject.author %>
        <small>
          <%= link_to notification.subject.author, root_path(filtered_params(author: notification.subject.author)), class: 'text-muted', title: 'Author', data: {toggle: 'tooltip'} %>
        </small>
      <% end %>
    <% end %>
  </td>

  <td class='notification-reason'>
    <%= link_to notification.reason.humanize, root_path(filtered_params(reason: notification.reason)), class: "badge badge-#{reason_label(notification.reason)}" %>
  </td>
  <td class='notification-date'>
    <small class='text-muted'>
      <%= local_relative_time(notification.updated_at, type: 'time-or-date') %>
    </small>

    <span class='buttons'>
      <% if notification.archived? %>
        <%= link_to(archive_selected_notifications_path(id: notification.id, value: false), method: :post, class: 'mr-1', 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Unarchive' ) do %>
          <%= octicon('inbox', height: 15) %>
        <% end %>
      <% else %>
        <%= link_to(archive_selected_notifications_path(id: notification.id), method: :post, class: 'mr-1', 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Archive' ) do %>
          <%= octicon('archive', height: 15) %>
        <% end %>
      <% end %>
      <%= link_to(mute_selected_notifications_path(id: notification.id), method: :post,  'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Mute' ) do %>
        <%= octicon('mute', height: 15) %>
      <% end %>
      <% if notification.archived? %>
        <%= link_to(delete_selected_notifications_path(id: notification.id), class: 'ml-1', method: :post, 'data-toggle': "tooltip", 'data-placement': "bottom", 'title': 'Delete' ) do %>
          <%= octicon('trashcan', height: 15) %>
        <% end %>
      <% end %>
    </span>
  </td>
</tr>

app/views/notifications/_private_repos.html.erb
<p>
  Enable pulling in state, labels, authors, assignees and CI status on issues and pull requests for private repositories by subscribing to a paid plan.
</p>

<a href='<%= pricing_path %>' class='btn btn-primary btn-sm'>Subscribe</a>

app/views/notifications/index.html.erb
<% if current_user.syncing? %>
  <span class="js-is_syncing"><!-- This causes the sync icon to spin --></span>
<% end %>
<span class='js-unread-count' data-count="<%= @unread_count %>"></span>

<div class="flex-content">
  <div class="flex-sidebar">
    <%= render "sidebar" %>
  </div>
  <div class="flex-main">
    <div class="card card-notifications justify-content-between">
      <div class="card-header sticky-top">
        <% if @notifications.to_a.any? %>
          <div class="per-page btn-group float-right d-block" data-toggle="tooltip" data-placement="left" title="Notifications per page">
            <button type="button" class="btn btn-sm btn-outline-dark dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= @per_page %>
              <span class="caret"></span>
            </button>
            <ul class="dropdown-menu dropdown-menu-right text-right">
              <% %w(20 40 60 80 100).map do |pagination_interval| %>
                <%= link_to pagination_interval, root_path(filtered_params(per_page: pagination_interval.to_i)), class: "dropdown-item #{'active' if @per_page == pagination_interval.to_i}" %>
              <% end %>
            </ul>
          </div>
        <% end %>
        <div class="btn btn-sm btn-link help float-right d-none d-md-inline-block" data-toggle="modal" data-target="#help-box">
          <%= octicon 'keyboard', :height => 16 %>
        </div>
        <button id='sidebar_toggle' type="button" class="d-inline-block d-lg-none btn btn-sm btn-outline-dark" data-toggle="offcanvas" aria-label='Toggle sidebar'>
          <%= octicon 'three-bars', :height => 16 %>
        </button>
        <% if @notifications.to_a.any? %>
          <div class="custom-control custom-checkbox select-all d-inline-block">
            <input id="select_all" type="checkbox" class='custom-control-input js-select_all' aria-label='Select All'>
            <%= label_tag "select_all", '', class: "custom-control-label" %>
          </div>
          <%= select_all_button(@cur_selected, @total) %>
        <% end %>
        <%= link_to sync_notifications_path(filters), class: "btn btn-sm btn-outline-dark js-sync #{'js-async' if Octobox.background_jobs_enabled?}", 'data-toggle' => 'tooltip', 'data-placement' => 'bottom', 'data-turbolinks' => false, 'data-animation' => 'false', 'data-position' => 'bottom', 'title' => 'Sync', 'aria-label' => 'Sync' do %>
          <%= octicon 'sync', height: 16, class: "#{'spinning' if initial_sync? || current_user.syncing?}" %>
        <% end %>
        <%= archive_selected_button unless archive_selected? %>
        <%= unarchive_selected_button unless inbox_selected? %>
        <%= mute_selected_button %>
        <%= mark_read_selected_button %>
        <%= delete_selected_button if archive_selected? %>
        <%= render 'filter-list' %>
        <% if current_user.last_synced_at %>
          <span class='text-muted d-none d-sm-inline-block'>
            <small>Last sync: <%= time_ago_in_words current_user.last_synced_at %> ago</small>
          </span>
        <% end %>
      </div>

      <table class='table table-hover table-notifications js-table-notifications mb-0 <%= 'filtered' if any_active_filters? %>' data-refresh-interval=<%= current_user.effective_refresh_interval %>>
        <% if @notifications.to_a.any? %>
          <%= render partial: 'notification', collection: @notifications %>
        <% elsif initial_sync? %>
          <div class="py-5 text-center js-initial_sync">
            <%= octicon 'cloud-download', height: 32, class: 'blankslate-icon' %>
            <h3>Syncing your notifications for the first time...</h3>
            <p>This might take a minute or two</p>
          </div>
          <% unless current_user.syncing? %>
            <span class="js-start_sync"><!-- This causes a sync to occur --></span>
          <% end %>
        <% elsif no_url_filter_parameters_present %>
          <div class="py-5 text-center">
            <%= octicon 'thumbsup', height: 32, class: 'blankslate-icon' %>
            <h3>You're in the clear!</h3>
            <p>There are no notifications that need your attention.</p>
            <p>
              <%= link_to sync_notifications_path(filters), method: :post, class: 'btn btn-outline-secondary sync' do %>
                <%= octicon 'sync', height: 18 %>
                <span class='ml-1'>Refresh</span>
              <% end %>
            </p>
            <% unless current_user.notifications.any? %>
              <p><i>Expecting notifications? Make sure <a href="<%= Octobox.config.github_domain %>/settings/notifications">Web Notifications</a> are enabled on your GitHub account.</i></p>
            <% end %>
            <% if current_user.last_synced_at %>
              <p class='text-muted'>
                <small>Last sync: <%= time_ago_in_words current_user.last_synced_at %> ago</small>
              </p>
            <% end %>
          </div>
        <% else %>
          <div class="py-5 text-center">
            <%= octicon 'search', height: 32, class: 'blankslate-icon' %>
            <h3>Nothing to see here.</h3>
            <p>You can always try <%= link_to 'refreshing', sync_notifications_path(filters), method: :post %> or <%= link_to 'removing filters', root_path %>.</p>
            <% unless current_user.notifications.any? %>
              <p><i>Expecting notifications? Make sure <a href="<%= Octobox.config.github_domain %>/settings/notifications">Web Notifications</a> are enabled on your GitHub account.</i></p>
            <% end %>
            <% if current_user.last_synced_at %>
              <p class='text-muted'>
                <small>Last sync: <%= time_ago_in_words current_user.last_synced_at %> ago</small>
              </p>
            <% end %>
          </div>
        <% end %>
      </table>
      <div class="card-footer d-block d-lg-none mb-0">
          <%= paginate @notifications, left: 1, right: 1, window: 0 %>
      </div>
    </div>

    <div class="d-none d-md-flex justify-content-center">
      <%= paginate @notifications %>
    </div>

    <%= render 'layouts/footer' %>
  </div>
</div>

<%= render 'help-box' %>