config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-status/web'
if Octobox.config.sidekiq_schedule_enabled?
  require 'sidekiq-scheduler/web'
end
require 'admin_constraint'

Rails.application.routes.draw do
  root to: 'notifications#index'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  constraints AdminConstraint.new do
    namespace :admin do
      mount Sidekiq::Web => "/sidekiq"
    end

    get '/admin', to: 'admin#index', as: :admin
  end

  get :login,  to: 'sessions#new'
  get :logout, to: 'sessions#destroy'

  scope :auth do
    match '/:provider/callback', to: 'sessions#create',  via: [:get, :post]
    match :failure,              to: 'sessions#failure', via: [:get, :post]
  end

  resources :notifications, only: :index, format: true, constraints: { format: :json }
  resources :notifications, only: [] do
    collection do
      post :archive_selected
      post :sync
      get  :sync
      get  :syncing
      post :mute_selected
      post :mark_read_selected
      get  :unread_count
      post :delete_selected
    end

    member do
      post :star
      post :mark_read
    end
  end

  get '/documentation', to: 'pages#documentation'
  get '/support', to: redirect('/documentation#support')

  post '/hooks/github', to: 'hooks#create'

  if Octobox.octobox_io?
    get '/pricing', to: 'pages#pricing'
    get '/privacy', to: 'pages#privacy'
    get '/terms', to: 'pages#terms'
  end

  resources :pinned_searches

  get '/settings', to: 'users#edit'
  resources :users, only: [:update, :destroy] do
    collection do
      scope format: true, constraints: { format: 'json' } do
        get :profile
      end
    end
  end
end

app/views/pages/_features.html.erb
<ul class="list-group list-group-flush pr-0">
	<li class="list-group-item mb-1"><%= octicon('check', class:'text-success') %> Unlimited private repositories</li>
	<li class="list-group-item mb-1"><%= octicon('check', class:'text-success') %> Unlimited public repositories</li>
	<li class="list-group-item mb-1"><%= octicon('check', class:'text-success') %> Unlimited collaborators</li>
</ul>

app/views/pages/_github.html.erb
<div class="pricing card mx-3 shadow p-3 mb-5 bg-white rounded text-muted">
  <div class="card-body">
  	<p class='text-muted'>GitHub Marketplace - coming soon</p>
    <h5 class="card-title">Support the company</h5>
    <h6 class="card-subtitle mb-2 text-muted">Buy from the GitHub marketplace.</h6>
    <p class="card-text">Private repository access</p>
    <%= render('features') %>
	  <div class='d-flex align-items-center border-top border-bottom py-2 mt-3 mb-3 d-flex flex-md-items-center flex-justify-between'>
	  	<span class="price pr-2">$100</span>
	  	<span class="text-small text-muted d-block mt-1 mt-md-0">/ month</span>
	  </div>
	  <a href='#' title='Coming soon' data-toggle='tooltip' class='btn btn-success w-100 disabled'>Purchase on GitHub</a>
	  <p class='text-muted'><small>Next: confirm your purchase on GitHub</small></p>
  </div>
</div>

app/views/pages/_opencollective.html.erb
<div class="pricing card mx-3 shadow p-3 mb-5 bg-white rounded">
  <div class="card-body">
  	<p class='text-muted'>Open Collective</p>
    <h5 class="card-title">Support the community</h5>
    <h6 class="card-subtitle mb-2 text-muted">Pay by donation on Open Collective.</h6>
    <p class="card-text">Private repository access</p>
    <%= render('features') %>
	  <div class='d-flex align-items-center border-top border-bottom py-2 mt-3 mb-3 d-flex flex-md-items-center flex-justify-between'>
	  	<span class="price pr-2">$100</span>
	  	<span class="text-small text-muted d-block mt-1 mt-md-0">/ month</span>
	  </div>
	  <a href='https://opencollective.com/octobox' target='_blank' class='btn btn-success w-100'>Donate on Open Collective</a>
	  <p class='text-muted'><small>Next: make your donation on Open Collective</small></p>
  </div>
</div>

app/views/pages/documentation.html.erb
<div class='flex-content'>
  <div class="flex-sidebar">
    <div id='sidebar' class="list-group list-group-flush flex-column pt-5">
      <a class='list-group-item list-group-item-action' href='#documentation'>Documentation</a>
      <a class='list-group-item list-group-item-action' href='#accessing'>Accessing Octobox</a>
      <a class='list-group-item list-group-item-action' href='#using'>Using Octobox</a>
      <a class='list-group-item list-group-item-action' href='#navigating'>Navigating Octobox</a>
      <a class='list-group-item list-group-item-action' href='#searching'>Searching Octobox</a>
      <a class='list-group-item list-group-item-action' href='#api'>API Documentation</a>
      <a class='list-group-item list-group-item-action' href='#support'>Support</a>
    </div>
  </div>

  <div class="flex-main">
    <div class="card">
      <div class='card-header d-lg-none sticky-top'>
        <button id='sidebar_toggle' type="button" class="btn btn-sm btn-outline-dark" data-toggle="offcanvas" aria-label='Toggle sidebar'>
          <%= octicon 'three-bars', :height => 16 %>
        </button>
      </div>
      <div class='card-body'>
        <h1 id='documentation' class="text-left">Documentation</h1>
        <hr>
        <p>
          Octobox helps you triage notifications efficiently so you can spend less time managing and more time getting things done.
        </p>
        <p>
          If you manage more than one active project on GitHub, you probably find <a href="https://github.com/notifications">GitHub Notifications</a> pretty lacking. Notifications are marked as read and disappear from the list as soon as you load the page or view the email of the notification. This makes it very hard to keep on top of which notifications you still need to follow up on. Most open source maintainers (and some GitHub staff) end up using a complex combination of filters and labels in their mail client to manage their notifications from their inbox. If, like us, you try to avoid email, then Octobox is for you.
        </p>
        <h2 id='accessing'>Accessing Octobox</h2>
        <hr>
        <% if Octobox.octobox_io? %>
          <p>
            This instance of Octobox is hosted by the Octobox.io team. To access Octobox.io you just need to sign in with your GitHub profile or install the GitHub app on the <%= link_to 'homepage', root_path %>.
          </p>
          <h3>Signing in with GitHub</h3>
          <p>
             This will give you access to basic notification information for public <i>and</i> private repositories using GitHub's <code>notification</code> scope. <% if Octobox.octobox_io? %> To access more detailed information you need to install the Octobox.io GitHub App. <% end %>
          </p>
          <% if Octobox.octobox_io? %>
            <h3>Installing the GitHub App</h3>
            <p>
              To access more detailed information about your notifications (assignees, labels, conversations threads etc) Octobox.io needs more privileged access to your repositories. To enable this you need to install our GitHub App for your personal or organisation's account. Access to public repositories on Octobox.io is free forever, access to private repositories is a paid-for service.
            </p>
            <h3>Paying for private repository access</h3>
            <p>
              There are two ways to pay for private repo access on Octobox.io:
            </p>
            <ul>
              <li>
                By making a donation of X or more each month to the Octobox community through <a href="https://opencollective.com/octobox">Open Collective</a>
              </li>
              <li>
                By paying X per Y through the GitHub Marketplace, which is charged monthly to your GitHub account.
              </li>
            </ul>
            <p>
              This may seem a little strange, but bear with us: As a social experiment in open source sustainability we are asking you to make a choice between supporting the community of maintainers and contributors, or supporting the commercial entity that operates Octobox.io. The service you'll receive will be <i>exactly the same</i> regardless of the way you pay. You can read more about why we think this is important <a href='#todo'>over on our blog</a>.
            </p>
          <% end %>
          <h3>Host your own Octobox</h3>
          <p>
            Alternatively you can host your own instance of Octobox. See <a href='#https://github.com/octobox/octobox/blob/master/docs/INSTALLATION.md'>the installation guide</a> for instructions and details regarding deployment to Heroku, Docker, and more.
          </p>
        <% end %>
        <% unless Octobox.octobox_io? %>
          <p>
            By default Octobox uses GitHub's basic OAuth <code>'notifications'</code> scope to access your notifications. This provides Octobox with access to notifications from both public <i>and</i> private repositories, but it provides very little detail about those notifications.
          </p>
          <p>
            In order to access more detailed information about your notifications Octobox needs to enable the <code>repo</code> scope on GitHub. You can do this by:
          </p>
          <ul>
            <li><a href='https://github.com/octobox/octobox/blob/master/docs/INSTALLATION.md#using-personal-access-tokens'>Using a personal access token</a></li>
            <li><a href='https://github.com/octobox/octobox/blob/master/docs/INSTALLATION.md#customizing-the-scopes-on-github'>Customising the GitHub scope environment variable</a></li>
          </ul>
        <% end %>
        <h2 id='using'>Using Octobox</h2>
        <hr>
        <p>
          Octobox helps you triage notifications from GitHub. If you use GitHub's own notifications dashboard you'll be familiar with some of the interface, actions etc. but there are some important differences:
        </p>
        <h3>Archiving</h3>
        <p>
          Octobox extends GitHub's notification model by providing an additional 'archived' status, much like Gmail's email client. Archived notifications will not appear in your inbox again unless the thread, issue or PR receives a new notification. Archiving a notification does not result in any action on GitHub.
        </p>
        <h3>Starring</h3>
        <p>
          Octobox also adds a starred status to help you highlight important notifications with a star so you can come back and find them easily. Starred notifications are not social, they are more like bookmarks that GitHub stars. Starring a notification does not result in any action on GitHub.
        </p>
        <h3>Muting</h3>
        <p>
          Muting a notification will mark the notification as read, move it to the archive <i>and</i> ignore all further notifications from this thread, issue or PR. Muting also sets the thread to <code>ignore:true</code> ignoring further notifications on GitHub too.
        </p>
        <h3>Syncing</h3>
        <p>
          By default Octobox will synchronise every time you hit the synchronise button.
          <% if Octobox.config.minimum_refresh_interval %>
            You can set automatic refresh interval on the <%= link_to 'settings page', settings_path %>.
          <% end %>
        </p>
        <h2>Shortcuts</h2>
        <hr>
        <p>
          Octobox features a full set of keyboard shortcuts inspired by Gmail:
        </p>
        <%= render 'shared/keyboard_mappings' %>
        <h2 id='navigating'>Navigating Octobox</h2>
        <hr>
        <p>
          The sidebar contains most of the things you'll need to navigate between views in Octobox:
        </p>
        <table class='table table-responsive'>
          <tr>
            <td>Archived</td>
            <td>Notifications that you've archived won't appear in your inbox again until Octobox receives another notification regarding that thread, issue or PR.</td>
          </tr>
          <tr>
            <td>
              Starred
            </td>
            <td>
              Notifications that you've starred are gathered together so you can come back and find them easily.
            </td>
          </tr>
          <tr>
            <td>
              Read/unread
            </td>
            <td>
              Notifications that have yet to be read or have been read, respectively. Nothing new here.
            </td>
          </tr>
          <tr>
            <td>
              Type
            </td>
            <td>
              Notifications by type (commit, issue, pull request, release, etc)
            </td>
          </tr>
          <tr>
            <td>
              Reason
            </td>
            <td>
              Notifications by the reason you've received it (assigned, authored, commented, mentioned, review requested, state changed or subscribed).
            </td>
          </tr>
          <tr>
            <td>
              Org/repo
            </td>
            <td>
              Notifications from a particular organisation and/or repo.
            </td>
          </tr>
          <tr>
            <td>
              State
            </td>
            <td>
              <%= repo_scope_modal %> The state of the underlying issue or PR. i.e. open, closed, merged,
            </td>
          </tr>
          <tr>
            <td>
              Assignee
            </td>
            <td>
              <%= repo_scope_modal %> Notifications assigned to you.
            </td>
          </tr>
          <tr>
            <td>
              Status
            </td>
            <td>
              <%= repo_scope_modal %> The current CI status of the underlying PR. i.e. Success, Failing, Pending
            </td>
          </tr>
          <tr>
            <td>
              Bots
            </td>
            <td>
             <%= repo_scope_modal %> Notifications created by bots.
            </td>
          </tr>
          <tr>
            <td>
              Unlabelled
            </td>
            <td>
              <%= repo_scope_modal %> Notifications that have not been labeled.
            </td>
          </tr>
          <tr>
            <td>
              Visibility
            </td>
            <td>
             <%= repo_scope_modal %> Notifications from public or private repositories.
            </td>
          </tr>
        </table>

        <h2 id='searching'>Searching Octobox</h2>
        <hr>
        <p>
          Octobox's search bar supports the following filter prefixes. Combine them together and with free text searches, for example: <code>"github enterprise type:issue owner:octobox reason:assign"</code>:
        </p>
        <p>
          Many prefixes accept multiple arguments when separated by commas or passed twice, for example:<br/>
          "<code>type:issue,release owner:octobox owner:24pullrequests</code>".
        </p>
        <p>
          Some prefixes also can be negated to exclude certain types of results, for example:<br/>
          "<code>-repo:splitrb/split -type:commit -owner:octobox -reason:mention</code>".
        </p>
        <h5>Supported prefixes</h5>
        <%= render 'shared/search_prefixes' %>

        <h2 id='api'>API Documentation</h2>
        <hr>
        <p>
          Access to the <a href='/docs'>Octobox API</a> requires a key which you can generate and regenerate from the <%= link_to 'settings page', settings_path %>.
        </p>

        <h2 id='support'>Support</h2>
        <hr>
        <p>
          Octobox.io is a small community of people supporting the service. We do not offer formal support processes. If you require formal support arrangements please <a href='mailto:support@octobox.io'>email us</a> otherwise you can try:
        </p>
        <ul>
          <li>Filing an issue in our <a href='https://github.com/octobox/octobox/issues/new'>bug tracker</a> following the template provided.</li>
          <li>Asking for help in our <a href='https://gitter.im/octobox/octobox'>public chat room</a>.</li>
          <li>Email us at <%= mail_to 'support@octobox.io' %>.</li>
          <li>Tweet us at <%= link_to '@octoboxio', 'https://twitter.com/octoboxio' %>.</li>
        </ul>
      </div>
    </div>
    <%= render 'layouts/footer'%>
  </div>
</div>

<%= render 'shared/repo_scope_modal' %>

app/views/pages/home.html.erb
<div class="container mt-5">
  <h1 class="text-center"><%= octobox_round(80) %> Octobox</h1>
  <p class="text-center">Untangle your GitHub Notifications</p>
  <div class="text-center ">
    <%= image_tag 'screenshot.png', class: 'screenshot', alt: 'Octobox Screenshot' %>
    <div class="row justify-content-center">
      <h4 class='mb-5 w-75  font-weight-light'>Octobox helps you manage your GitHub notifications efficiently so you can spend less time managing and more time getting things done.</h4>
    </div>
    <p>
      <%= link_to login_path, class: 'btn btn-outline-dark btn-lg' do %>
        <%= octicon 'mark-github', height: 22 %>
        <span class='ml-1'>Sign in with GitHub</span>
      <% end %>
      <% if Octobox.github_app? %>
        <%= link_to Octobox.config.app_url, class: 'btn btn-outline-dark btn-lg' do %>
          <%= octicon 'briefcase', height: 22 %>
          <span class='ml-1'>Install the GitHub App</span>
        <% end %>
      <% end %>
    </p>
    <p>
      <a class="github-button" href="https://github.com/octobox/octobox" data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star octobox/octobox on GitHub">Star</a>
      <a class="github-button" href="https://github.com/octobox/octobox/fork" data-icon="octicon-repo-forked" data-size="large" data-show-count="true" aria-label="Fork octobox/octobox on GitHub">Fork</a>
    </p>
  </div>

  <div class="row mb-5 mt-5">
    <div class="col-lg-6">
      <div class="card shadow-sm mb-3">
        <div class="card-content">
          <div class="card-body">
            <div class="media d-flex">
              <div class="align-self-center mr-4">
                <%= octicon 'inbox', height: 50 %>
              </div>
              <div class="media-body">
                <h4>Don't lose track</h4>
                Octobox adds an extra "archived" state to each notification so you can mark it as "done". If anything happens on an archived thread, issue or PR, Octobox will move it back into your inbox.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="card shadow-sm mb-3">
        <div class="card-content">
          <div class="card-body">
            <div class="media d-flex">
              <div class="align-self-center mr-4">
                <%= octicon 'star', height: 50 %>
              </div>
              <div class="media-body">
                <h4>Starred notifications</h4>
                Let's be honest, you probably don't have a 'favourite' issue but Octobox lets you highlight important notifications with a star so you can come back and find them easily.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="card shadow-sm mb-3">
        <div class="card-content">
          <div class="card-body">
            <div class="media d-flex">
              <div class="align-self-center mr-4">
                <%= octicon 'settings', height: 50 %>
              </div>
              <div class="media-body">
                <h4>Filter all the things</h4>
                Filter notifications by notification type, action, state and reason and keep notifications from bots alongside your regular label, author and assignees.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="card shadow-sm mb-3">
        <div class="card-content">
          <div class="card-body">
            <div class="media d-flex">
              <div class="align-self-center mr-4">
                <%= octicon 'search', height: 50 %>
              </div>
              <div class="media-body">
                <h4>Search with prefix filters</h4>
                No more Jedi mind tricks. Combine a wide range of powerful search filters help you get straight to the notification you're looking for and focus on just what you need.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="card shadow-sm mb-3">
        <div class="card-content">
          <div class="card-body">
            <div class="media d-flex">
              <div class="align-self-center mr-4">
                <%= octicon 'keyboard', height: 50 %>
              </div>
              <div class="media-body">
                <h4>Built for keyboard warriors</h4>
                Navigate, triage and manage your notifications like a pro using Gmail-inspired keyboard shortcuts for every function, no mouse required.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="col-lg-6">
      <div class="card shadow-sm mb-3">
        <div class="card-content">
          <div class="card-body">
            <div class="media d-flex">
              <div class="align-self-center mr-4">
                <%= octicon 'mark-github', height: 50 %>
              </div>
              <div class="media-body">
                <h4>Open for everyone</h4>
                Octobox developers use Octobox to develop Octobox. 100% developed and managed in the open on GitHub under a FLOSS license.
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

  <h3>Used by developers from top organisations</h3>
  <div class="row mb-5 mt-4">
    <div class="col">
      <% used_by_orgs.each do |org| %>
        <%= image_tag "https://github.com/#{org}.png?w=120", width: 60, height: 60, class: 'inline-block mr-2 mb-3', title: org, data: {toggle: 'tooltip'} %>
      <% end %>
    </div>
  </div>

  <div class="row justify-content-center text-large">
    <div class="col-lg-12">
      <h3>Why is this a thing?</h3>
      <p>
        Octobox helps you triage notifications efficiently so you can spend less time managing and more time getting things done.
      </p>
      <p>
        If you manage more any active projects on GitHub, you probably find <a href="https://github.com/notifications">GitHub Notifications</a> pretty lacking. Notifications are marked as read and disappear from the list as soon as you load the page or view the email of the notification. This makes it very hard to keep on top of which notifications you still need to follow up on. Most open source maintainers and GitHub staff end up using a complex combination of filters and labels in Gmail to manage their notifications from their inbox. If, like me, you try to avoid email, then you might want something else.
      </p>
      <p>
        Octobox adds an extra "archived" state to each notification so you can mark it as "done". If new activity happens on the thread/issue/pr, the next time you sync the app the relevant item will be unarchived and moved back into your inbox.
      </p>

      <h3>Run your own Octobox</h3>

      <p>The Octobox team hosts a shared instance of Octobox at <a href="https://octobox.io/">octobox.io</a>, but perhaps you're looking to host your own or get yourself set up to contribute to Octobox. Fantastic! There are a number of install options available to you, check out the <a href="https://github.com/octobox/octobox/blob/master/docs/INSTALLATION.md">installation guide</a>.</p>

      <h3>Contribute</h3>

      <p>Octobox is open source and the source code is hosted at <a href="https://github.com/octobox/octobox">GitHub</a>. If you have an idea for a feature or enhancement, open an <a href="https://github.com/octobox/octobox/issues/new">issue</a> or a pull request.</p>

      <p>If you want to contribute you'll find we're a welcoming bunch. If you don't know where to start, take a look at the issues tagged as <a href="https://github.com/octobox/octobox/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22">"Help Wanted"</a>.</p>

      <p>You can also help triage issues. This can include reproducing bug reports, or asking for vital information such as version numbers or reproduction instructions. If you would like to start triaging issues, one easy way to get started is to <a href="https://www.codetriage.com/octobox/octobox">subscribe to Octobox on CodeTriage</a>.</p>

      <p>Finally, this is an open source project. If you would like to become a maintainer, we will consider adding you if you contribute frequently to the project. Feel free to ask.</p>

    </div>
  </div>
</div>

<%= render 'layouts/footer'%>
<script async defer src="https://buttons.github.io/buttons.js"></script>

app/views/pages/pricing.html.erb
<div class='container mt-5'>
	<h1 class="text-center"><%= octobox_round(80) %> Octobox</h1>
	<h3 class='text-center pt-3'>One product, two ways to pay</h3>
	<div class='d-flex flex-column flex-lg-row pt-3 px-3 pb-3 justify-content-center'>
		<%= render('opencollective')%>
		<%= render('github')%>
	</div>
	<div class='container readable mb-5'>
		<h2 class='text-center mb-5'>What... Why?</h2>

		<h5>An experiment in open source sustainability</h5>

    <p>Like many open source projects Octobox currently relies on volunteers and donations to cover the cost of maintaining the Octobox project. This is <a href='https://www.fordfoundation.org/about/library/reports-and-studies/roads-and-bridges-the-unseen-labor-behind-our-digital-infrastructure/'>not sustainable</a>.

    <p>Octobox is primarily maintained by Andrew Nesbitt and Benjamin Nickolls. We believe that many of the issues around the sustainability of open source software <i>can</i> be solved by the community itself. We also believe in leading by example, testing our assumptions and backing up our decisions with data.</p>

    <p>Octobox has a small community of <a href='https://github.com/orgs/octobox/people'>maintainers</a>, <a href='https://github.com/octobox/octobox/graphs/contributors'>contributors</a>, <a href='https://opencollective.com/octobox/#contributors'>supporters and sponsors</a>. Our first priority is to begin building a sustainable income, for ourselves and our community. Our second is to demonstrate that our approach is repeatable and scalable, proving that we can solve this problem <i>together</i>. Our pricing model is our first experiment.

    <h5 class='pt-3'>Do you prefer supporting a commercial provider, or the community itself?</h5>
    <p>Octobox.io operated by Octobox Ltd. a company registered in the UK by Andrew Nesbitt and Benjamin Nickolls. The company is primarily designed to offer limited liability to the operators of Octobox.io and to renumerate directors and staff as employees or contractors.</p>

    <p>The Octobox project will continue to collect donations via Open Collective and operate a transparent ledger of income and outgoings for the project — including, for the time being, the costs of hosting Octobox.io. When it is able the project will pay maintainers for their time including time spent operating Octobox.io, which will be directed through Octobox Ltd.</p>

    <p>Octobox Ltd. will provide private repository access to those who donate an equivalent sum (or more) to the community as pay directly through alternate channels. In addition the company will pledge at least 15% of its revenues for use by the community to further the open source project, forever.</p>

    <h5 class='pt-3'>Why does this matter?</h5>

    <p>Most open source projects struggle to navigate the legislative, legal and social issues around sustianing their projects. By diving straight into the deep end and documenting our experiences we hope to provide a blueprint for others to follow.</p>

    <p>By asking you to make the choice with how you pay we will demonstrate whether donation-based, community-first sustainabiliy strategies work over more classical, commercial-lead approaches.</p>

    <p>Thanks for taking the time to read this. If anything is unclear or you have concerns about this please <a href='https://github.com/octobox/octobox/issues/new'>raise an issue</a> or <a href='mailto: hello@octobox.io'>get in touch</a>.</p>

	</div>
</div>

<%= render 'layouts/footer'%>