config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'
require 'sidekiq-status/web'
if Octobox.config.sidekiq_schedule_enabled?
  require 'sidekiq-scheduler/web'
end
require 'admin_constraint'

Rails.application.routes.draw do
  root to: 'notifications#index'

  get '/404', to: 'errors#not_found'
  get '/422', to: 'errors#unprocessable'
  get '/500', to: 'errors#internal'

  constraints AdminConstraint.new do
    namespace :admin do
      mount Sidekiq::Web => "/sidekiq"
    end

    get '/admin', to: 'admin#index', as: :admin
  end

  get :login,  to: 'sessions#new'
  get :logout, to: 'sessions#destroy'

  scope :auth do
    match '/:provider/callback', to: 'sessions#create',  via: [:get, :post]
    match :failure,              to: 'sessions#failure', via: [:get, :post]
  end

  resources :notifications, only: :index, format: true, constraints: { format: :json }
  resources :notifications, only: [] do
    collection do
      post :archive_selected
      post :sync
      get  :sync
      get  :syncing
      post :mute_selected
      post :mark_read_selected
      get  :unread_count
      post :delete_selected
    end

    member do
      post :star
      post :mark_read
    end
  end

  get '/documentation', to: 'pages#documentation'
  get '/support', to: redirect('/documentation#support')

  post '/hooks/github', to: 'hooks#create'

  if Octobox.octobox_io?
    get '/pricing', to: 'pages#pricing'
    get '/privacy', to: 'pages#privacy'
    get '/terms', to: 'pages#terms'
  end

  resources :pinned_searches

  get '/settings', to: 'users#edit'
  resources :users, only: [:update, :destroy] do
    collection do
      scope format: true, constraints: { format: 'json' } do
        get :profile
      end
    end
  end
end

app/views/layouts/_favicons.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
<link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
<link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
<link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
<link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
<link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
<link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
<link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link id="favicon" rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<link rel="manifest" href="/manifest.json">
<link rel="mask-icon" href="<%= asset_path "infinitacle.svg" %>" color="black">
<meta name="msapplication-TileColor" content="#ffffff">
<meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
<meta name="theme-color" content="#ffffff">

app/views/layouts/_footer.html.erb
<div class="footer text-muted small mt-3">
  <p>
    © 2018 <a href='https://github.com/andrew' >Andrew Nesbitt</a>,
    <%= link_to 'et al', "#{Octobox.config.source_repo}/graphs/contributors", target: '_blank', rel: "noopener" %>
    &mdash;
    Logo by
    <%= link_to 'Raeha Keller', "https://www.etsy.com/uk/people/PrincessRaeha", target: '_blank', rel: "noopener" %> 
    &mdash;
    <%= link_to 'Source', Octobox.config.source_repo, target: '_blank', rel: "noopener" %>
    available under
    <%= link_to 'AGPL 3.0', "#{Octobox.config.source_repo}/blob/master/LICENSE.txt", target: '_blank', rel: "noopener" %>
    <% if Octobox.octobox_io? %>
      &mdash; <a href='/terms' target="_blank" rel="noopener">Terms</a> &amp; <a href='/privacy' target="_blank" rel="noopener">Privacy Policy</a>
    <% end %>
  </p>
</div>

app/views/layouts/_header.html.erb
<nav class='navbar navbar-dark bg-dark navbar-fixed-top navbar-expand-md'>
  <a class="navbar-brand" href="/" title='Octobox'>
    <%= octobox_reverse_icon(18) %>
  </a>
  <div class="position-relative dropdown">
    <div>
      <button class="btn btn-dark navbar-toggler search-toggler" type="button" data-toggle="collapse" data-target="#search" aria-controls="search" aria-expanded="false" aria-label="Toggle search">
        <span class="sr-only">Toggle search</span>
        <%= octicon 'search', height: 16, class: 'text-muted' %>
      </button>
      <button id='navbarnav_toggle' class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="sr-only">Toggle navigation</span>
        <% if current_user %>
          <%= image_tag current_user.github_avatar_url + "?size=64", width: 32, height:32, class: 'img-rounded navbar-avatar', alt: '' %>
        <% else %>
          <%= octicon 'three-bars', height: 16, class: 'text-muted' %>
        <% end %>
      </button>
    </div>
  </div>
  <% if @notifications %>
    <%= form_tag root_path, method: :get, class: 'form-inline collapse navbar-collapse', id: 'search', enforce_utf8: false do |f| %>
      <div class="search-sugguestion-section d-inline-flex justify-content-between align-items-center w-100">
        <div class="search-input-box position-relative d-flex align-items-center w-100">
          <%= text_field_tag 'q', @search.to_query, placeholder: 'Search...', class: 'custom-input form-control', id: 'search-box', 'aria-label' => 'Search', :autocomplete => "off" %>
          <div class="btn btn-sm btn-link search-help d-none d-md-block" title='Search Cheat Sheet' data-toggle="modal" data-target="#search-help">
            <%= octicon 'question', :height => 16 %>
          </div>
          <div class="search-sugguestion-section d-inline-flex justify-content-between align-items-center">
            <ul id="search-sugguestion-list" class="form-inline__section search-dropdown d-none">
            </ul>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
  <div class="user-info collapse navbar-collapse justify-content-end" id="navbarNav">
    <ul class="navbar-nav">
      <li class="nav-item nav-link d-none d-md-block">
        <% if Octobox.octobox_io? %>
          <a href="<%= Octobox.config.app_url %>" class='btn btn-sm btn-outline-light'>
            <%= octicon 'briefcase', height: 16, class: 'mr-1' %>
            Install the GitHub App
          </a>
        <% else %>
          <a href="https://opencollective.com/octobox/" class='opencollective' target='_blank' rel="noopener" aria-label='Support Octobox on OpenCollective'>
            <%= octicon 'gift', height: 16, data: {toggle: "tooltip", placement: "bottom"}, title: 'Support Octobox on OpenCollective' %>
          </a>
        <% end %>
      </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle d-none d-md-block" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <span class="navbar-avatar-fixed-width">
            <%= image_tag current_user.github_avatar_url + "?size=40", width: 20, class: 'img-rounded navbar-avatar', alt: '' %>
          </span>
        </a>
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
          <%= link_to "#{Octobox.config.github_domain}", class: 'dropdown-item', target: "_blank", rel: "noopener" do %>
            <%= octicon 'mark-github', height: 16, class: 'text-muted' %>
            GitHub Dashboard
          <% end %>
          <%= link_to documentation_path(anchor: 'support'), class: 'dropdown-item', target: "_blank", rel: "noopener" do %>
            <%= octicon 'question', height: 16, class: 'text-muted' %>
            Octobox Support
          <% end %>
          <% if current_user.admin? %>
            <%= link_to admin_path, class: 'dropdown-item' do %>
              <%= octicon 'gist-secret', height: 16, class: 'text-muted' %>
              Admin
            <% end %>
            <% if Octobox.background_jobs_enabled? %>
              <%= link_to admin_sidekiq_web_path, class: 'dropdown-item' do %>
                <%= octicon 'graph', height: 16, class: 'text-muted' %>
                Sidekiq
              <% end %>
            <% end %>
          <% end %>
          <%= link_to "documentation", class: 'dropdown-item' do %>
            <%= octicon 'book', height: 16, class: 'text-muted' %>
            User Documentation
          <% end %>
           <% if Octobox.config.native_link %>
              <%= link_to Octobox.config.native_link, class: 'dropdown-item' do %>
                <%= octicon 'desktop-download', height: 16, class: 'text-muted' %>
                Download Desktop App
              <% end %>
          <% end %>
          <% if File.exist?(Rails.root.join('public', 'docs', 'index.html')) %>
            <%= link_to "docs/", class: 'dropdown-item' do %>
              <%= octicon 'code', height: 16, class: 'text-muted' %>
              API Documentation
            <% end %>
          <% end %>
          <%= link_to "settings", class: 'dropdown-item' do %>
            <%= octicon 'settings', height: 16, class: 'text-muted' %>
            Settings
          <% end %>
          <div class="dropdown-divider d-md-none"></div>
          <a class="d-md-none" href="https://opencollective.com/octobox/" class='opencollective' target='_blank' rel="noopener"><%= octicon 'gift', height: 16, class: 'text-muted' %> Donate</a>
          <div class="dropdown-divider"></div>
          <%= link_to logout_path, class: 'dropdown-item' do %>
            <%= octicon 'sign-out', height: 16, class: 'text-muted' %>
            Logout
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Octobox</title>
    <%= csrf_meta_tags %>

    <%= render 'layouts/favicons' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="turbolinks-cache-control" content="no-preview">
    <meta name="Description" content="Untangle your GitHub Notifications">

    <link rel="preconnect" href="https://api.github.com">

    <% if Rails.env.production? && Rails.application.secrets.google_analytics_id.present? %>
      <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
        (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
        m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
        ga('create', '<%= Rails.application.secrets.google_analytics_id %>', 'auto');
      </script>
    <% end %>

    <% if Rails.application.secrets.bugsnag_js_api_key.present? %>
      <script src="//d2wy8f7a9ursnm.cloudfront.net/v4/bugsnag.min.js"></script>
      <script>window.bugsnagClient = bugsnag({ apiKey: '<%= Rails.application.secrets.bugsnag_js_api_key %>', releaseStage: '<%= ENV["RAILS_ENV"] %>' })</script>
    <% end %>

    <%= stylesheet_link_tag  current_theme, media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>

    <meta property="og:title" content="Octobox">
    <meta property="og:description" content="Untangle your GitHub Notifications">
    <meta property="og:image" content="<%= asset_url 'app-icon.png' %>">
    <meta property="og:url" content="<%= root_url %>">
    <meta property="og:type" content="article" />
    <meta property="og:site_name" content="Octobox" />

    <meta name="twitter:card" content="summary">
    <meta name="twitter:creator" content="teabass">
  </head>

  <body>
    <% if logged_in? %>
      <div class="flex-header">
        <%= render 'layouts/header' %>
      </div>
    <% end %>

    <%= flash_messages %>

    <%= yield %>

    <% if logged_in? %>
      <%= render 'notifications/search-help' %>
    <% end %>

    <% if Rails.env.production? && Rails.application.secrets.google_analytics_id.present? %>
      <script>
        if (typeof ga === 'function') { ga('send', 'pageview', location.pathname+location.search) }
      </script>
    <% end %>
  </body>
</html>